version: '3.8'

services:
  app:
    # Указываем, что образ нужно собирать из текущей папки
    # используя Dockerfile.production
    build:
      context: .
      dockerfile: Dockerfile.production
    
    container_name: hr_bot_app
    restart: unless-stopped
    
    # Указываем, что переменные окружения нужно брать из файла .env
    env_file: .env
    
    # Пробрасываем порт, чтобы веб-часть была доступна снаружи
    ports:
      - "5000:5000"
      
    # Подключаем папки для логов и загрузок
    volumes:
      - ./logs:/app/logs
      - ./uploads:/app/uploads
      
    # Настраиваем логирование
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
